# Generated by Django 3.2rc1 on 2021-07-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlcherStream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockbuster',
            name='userid',
        ),
    ]
