# Generated by Django 3.2rc1 on 2021-07-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='movie_id',
        ),
    ]
