# Generated by Django 3.2rc1 on 2021-07-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_favorites_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
