# Generated by Django 3.2rc1 on 2021-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_favorites_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='userid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
