# Generated by Django 3.2rc1 on 2021-07-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=500)),
                ('who_commented', models.CharField(default='', max_length=10)),
                ('what_commented', models.TextField(default='')),
                ('when_commented', models.DateTimeField()),
            ],
        ),
    ]
