# Generated by Django 3.2rc1 on 2021-07-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='what_commented',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
